### ISSUE TITLE
create a collection of background images

### ISSUE THREAD

**Issue by maxbransontaylor** [maxbransontaylor/genre-buddy#11]
use something like https://unsplash.com/ and save a collection of images we'd want to use as backgrounds to the images folder
we need high-resolution images depicting popular genres ex. horror, action, fantasy, sci-fi, mystery, etc.

**Comment by GDM8** [comment]
# Create A Collection Of Background Images

## Content Requirments
* use something like https://unsplash.com/ and save a collection of images we'd want to use as backgrounds to the images folder
* we need high-resolution images depicting popular genres ex. horror, action, fantasy, sci-fi, mystery, etc.

## Issue resolved

* Background image assets pushed to develop branch
* image addresses saved
